### ISSUE TITLE
add offline astrometry support

### ISSUE THREAD

**Issue by trlsmax** [ThemosTsikas/PhotoPolarAlign#4]
Hi
Can you consider add offline local astrometry installation support ?

**Comment by ThemosTsikas** [comment]
Hello, 
If I understand you correctly, there is support already for a Windows (say) Cygwin installation of astrometry.net. I am aware of 3 ways you can easily get this: Astrotortilla, AllSkyPlateSolver and Ansvr. The last one has a web interface just like nova.astrometry so PPA can be used immediately with a one line code change, directing to 127.0.0.1:8080 instead of nova.astrometry.net

**Comment by wvreeven** [comment]
I managed to install the astrometry.net software on my MacBook using homebrew and extracted the perl files that form the Ansvr server from the Windows/Cygwin files. So now I can run everything offline. It would be nice though if the URL for the astrometry.net api could be configurable via a cfg file instead of having to modify the PPA.py file.
